FROM fluent/fluentd:latest
MAINTAINER kxw <xw.kong@hnair.com>
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

# cutomize following "gem install fluent-plugin-..." line as you wish
#docker build -t custom-fluentd:latest ./

USER root
RUN \
    gem install fluent-plugin-elasticsearch  fluent-plugin-record-modifier fluent-plugin-kafka  fluent-plugin-redis fluent-plugin-burrow 
EXPOSE 24224
COPY fluent.conf /fluentd/etc/
CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
