FROM nginx_flt6
MAINTAINER kxw <xw.kong@hnair.com>
LABEL Description="nginx image within fluentd" Vendor="HNA Organization" Version="1.1"
#COPY  docker-entrypoint.sh /usr/local/bin/
COPY  fluent.conf /fluentd/etc/ 
